@echo off
ECHO "=--------------------------------------------------="
ECHO "|              NIVLang Logo             			 |"
ECHO "=--------------------------------------------------="
ECHO "NNNNNNNN        NNNNNNNNVVVVVVVV           VVVVVVVV ”
ECHO "N:::::::N       N::::::NV::::::V           V::::::V ”
ECHO "N::::::::N      N::::::NV::::::V           V::::::V ”
ECHO "N:::::::::N     N::::::NV::::::V           V::::::V ”
ECHO "N::::::::::N    N::::::N V:::::V           V:::::V  ”
ECHO "N:::::::::::N   N::::::N  V:::::V         V:::::V   ”
ECHO "N:::::::N::::N  N::::::N   V:::::V       V:::::V    ”
ECHO "N::::::N N::::N N::::::N    V:::::V     V:::::V	  ”
ECHO "N::::::N  N::::N:::::::N     V:::::V   V:::::V 	  ”
ECHO "N::::::N   N:::::::::::N      V:::::V V:::::V		  ”
ECHO "N::::::N    N::::::::::N       V:::::V:::::V		  ”
ECHO "N::::::N     N:::::::::N        V:::::::::V		  ”
ECHO "N::::::N      N::::::::N         V:::::::V	  	  ”
ECHO "N::::::N       N:::::::N          V:::::V			  ”
ECHO "N::::::N        N::::::N           V:::V	   		  ”
ECHO "NNNNNNNN         NNNNNNN            VVV	 	      ”
ECHO "=================================================== ”
ECHO "|             Lightweight & Fast                  | "
ECHO "===================================================="                                         "
ECHO "Clear script========================================"
ECHO "                                         "


DEL *.OUT
DEL *.ERR
pause